add junit test result in github

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -21,7 +21,12 @@ jobs:
       - name: Install modules
         run: npm ci
       - name: Run tests
-        run: npm run test
+        run: npm run test:ci
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "junit.xml"
 
   lint:
     runs-on: ubuntu-latest
