refacto: remove oop, add better tests, use ddd (#1)
* refacto: remove oop, add better tests, use ddd

* add junit test result in github

* ci: try to fix test report publish

* ci: try to fix test report publish

* ci: test with failed test

* ci: fix tests

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -15,6 +15,8 @@ jobs:
     defaults:
       run:
         working-directory: ./app
+    permissions:
+      checks: write
     steps:
       - name: Setup repo
         uses: actions/checkout@v4
@@ -22,6 +24,11 @@ jobs:
         run: npm ci
       - name: Run tests
         run: npm run test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/junit.xml"
 
   lint:
     runs-on: ubuntu-latest
